import cron from 'node-cron';
import DailyPnL from '../models/DailyPnL.js';
import Invoice from '../models/Invoice.js';
import SalesOrder from '../models/SalesOrder.js';
import ProductionBatch from '../models/ProductionBatch.js';
import PettyCash from '../models/PettyCash.js';
import Bill from '../models/Bill.js';
import excelService from './excelService.js';

let _io = null;

/**
 * Calculate Daily P&L breakdown for a specific date
 * @param {string|Date} dateStr - Date to compute P&L for
 * @returns {Promise<Object>}
 */
export async function calculatePnLForDate(dateStr) {
    const start = new Date(dateStr);
    start.setHours(0, 0, 0, 0);
    const end = new Date(dateStr);
    end.setHours(23, 59, 59, 999);

    // 1. Invoices & Sales Orders
    const invoices = await Invoice.find({
        deletedAt: null,
        invoiceType: { $ne: 'proforma' },
        status: { $nin: ['draft', 'cancelled'] },
        invoiceDate: { $gte: start, $lte: end }
    });
    const invoiceRev = invoices.reduce((sum, inv) => sum + (inv.grandTotal || 0), 0);

    const orders = await SalesOrder.find({
        deletedAt: null,
        status: { $nin: ['draft', 'cancelled'] },
        orderDate: { $gte: start, $lte: end }
    });
    const orderRev = orders.reduce((sum, o) => sum + (o.grandTotal || 0), 0);
    const totalRevenue = invoiceRev > 0 ? invoiceRev : orderRev;

    // 2. Production Batches
    const batches = await ProductionBatch.find({
        deletedAt: null,
        date: { $gte: start, $lte: end }
    }).populate('supplierId', 'isOwnFarm internalTransferPrice');

    let batchRawMaterial = 0;
    let batchLabour = 0;
    let batchFirewood = 0;
    batches.forEach(b => {
        const rate = b.supplierId?.isOwnFarm ? (b.supplierId.internalTransferPrice || 0) : 0;
        batchRawMaterial += (b.materialCost || (b.inputWeight_total * rate) || 0);
        batchLabour += (b.laborCost || 0);
        batchFirewood += ((b.firewoodKg_day || 0) + (b.firewoodKg_night || 0));
    });

    // 3. Petty Cash
    const pettyCashExpenses = await PettyCash.find({
        deletedAt: null,
        transactionType: 'expense',
        date: { $gte: start, $lte: end }
    });
    const pettyRawMaterial = pettyCashExpenses.reduce((sum, pc) => sum + (pc.rawMaterial_cost || 0), 0);
    const pettyLabour = pettyCashExpenses.reduce((sum, pc) => sum + (pc.miscWages || 0), 0);
    const firewood = pettyCashExpenses.reduce((sum, pc) => sum + (pc.wood || 0), 0) + batchFirewood;
    const packing = pettyCashExpenses.reduce((sum, pc) => sum + (pc.packingMaterials || 0), 0);
    const transport = pettyCashExpenses.reduce((sum, pc) => sum + (pc.transport || 0), 0);
    const other = pettyCashExpenses.reduce((sum, pc) => {
        return sum + (pc.welfare || 0) + (pc.fuel || 0) + (pc.maintenance || 0) + (pc.stationary || 0) + (pc.chemicals || 0);
    }, 0);

    // 4. Bills (Supplier purchases)
    const bills = await Bill.find({
        deletedAt: null,
        billDate: { $gte: start, $lte: end },
        status: { $nin: ['draft', 'cancelled'] }
    });
    const billRawMaterial = bills.reduce((sum, b) => sum + (b.totalAmount || 0), 0);

    const rawMaterial = batchRawMaterial + pettyRawMaterial + billRawMaterial;
    const labourSalary = batchLabour + pettyLabour;
    const totalExpenses = rawMaterial + labourSalary + firewood + packing + transport + other;
    const netProfit = totalRevenue - totalExpenses;
    const marginPercent = totalRevenue > 0 ? +((netProfit / totalRevenue) * 100).toFixed(2) : 0;

    return {
        date: start,
        day: start.getDate(),
        totalRevenue: +totalRevenue.toFixed(2),
        rawMaterial: +rawMaterial.toFixed(2),
        labourSalary: +labourSalary.toFixed(2),
        supervisorQC: 0,
        electricity: 0,
        firewood: +firewood.toFixed(2),
        packing: +packing.toFixed(2),
        transport: +transport.toFixed(2),
        communication: 0,
        other: +other.toFixed(2),
        totalExpenses: +totalExpenses.toFixed(2),
        netProfit: +netProfit.toFixed(2),
        marginPercent
    };
}

/**
 * Auto-generate and upsert Daily P&L records for all active dates or within a date range
 * @param {Object} options - { startDate, endDate, userId }
 * @returns {Promise<Array>} List of generated DailyPnL records
 */
export async function autoGenerateDailyPnLRecords(options = {}) {
    const { startDate, endDate, userId } = options;

    const dateFilter = {};
    if (startDate) dateFilter.$gte = new Date(startDate);
    if (endDate) dateFilter.$lte = new Date(endDate);

    const hasRange = !!(startDate || endDate);

    // Find all distinct active dates across sources
    const [invoiceDates, batchDates, cashDates, billDates] = await Promise.all([
        Invoice.distinct('invoiceDate', { deletedAt: null, ...(hasRange ? { invoiceDate: dateFilter } : {}) }),
        ProductionBatch.distinct('date', { deletedAt: null, ...(hasRange ? { date: dateFilter } : {}) }),
        PettyCash.distinct('date', { deletedAt: null, transactionType: 'expense', ...(hasRange ? { date: dateFilter } : {}) }),
        Bill.distinct('billDate', { deletedAt: null, ...(hasRange ? { billDate: dateFilter } : {}) })
    ]);

    const activeDateStrings = Array.from(new Set(
        [...invoiceDates, ...batchDates, ...cashDates, ...billDates]
            .filter(Boolean)
            .map(d => new Date(d).toISOString().slice(0, 10))
    )).sort();

    const generatedRecords = [];
    const chunkSize = 20;

    for (let i = 0; i < activeDateStrings.length; i += chunkSize) {
        const chunk = activeDateStrings.slice(i, i + chunkSize);
        const results = await Promise.all(chunk.map(d => calculatePnLForDate(d)));

        const bulkOps = [];
        for (const calculated of results) {
            if (calculated.totalRevenue === 0 && calculated.totalExpenses === 0) {
                continue;
            }

            const startOfDay = new Date(calculated.date);
            startOfDay.setHours(0, 0, 0, 0);
            const endOfDay = new Date(calculated.date);
            endOfDay.setHours(23, 59, 59, 999);

            bulkOps.push({
                updateOne: {
                    filter: {
                        date: { $gte: startOfDay, $lte: endOfDay },
                        deletedAt: null
                    },
                    update: {
                        $set: {
                            ...calculated,
                            ...(userId ? { updatedBy: userId } : {})
                        }
                    },
                    upsert: true
                }
            });
            generatedRecords.push(calculated);
        }

        if (bulkOps.length > 0) {
            await DailyPnL.bulkWrite(bulkOps);
        }
    }

    if (_io && generatedRecords.length > 0) {
        _io.emit('financial_update', { type: 'daily_pnl_autogenerated', count: generatedRecords.length });
    }

    return generatedRecords;
}

/**
 * Initialize daily scheduled cron to auto-generate today's P&L
 */
export function initDailyPnLScheduler(io) {
    _io = io;

    // Run daily at 23:55 (11:55 PM) to calculate and upsert today's P&L
    cron.schedule('55 23 * * *', async () => {
        console.log('[DailyPnL] Running scheduled auto-generation for today...');
        try {
            const todayStr = new Date().toISOString().slice(0, 10);
            const records = await autoGenerateDailyPnLRecords({ startDate: todayStr, endDate: todayStr });
            console.log(`[DailyPnL] Scheduled calculation completed. ${records.length} record(s) processed.`);
        } catch (err) {
            console.error('[DailyPnL] Scheduled auto-generation error:', err.message);
        }
    });

    console.log('[DailyPnL] Daily P&L auto-generator scheduler initialised (runs daily at 23:55)');
}

export default {
    calculatePnLForDate,
    autoGenerateDailyPnLRecords,
    initDailyPnLScheduler
};
