import DailyPnL from '../models/DailyPnL.js';
import excelService from '../services/excelService.js';
import { calculatePnLForDate, autoGenerateDailyPnLRecords } from '../services/dailyPnLAutoService.js';

export const getPnLRecords = async (req, res) => {
    try {
        const records = await DailyPnL.find({ deletedAt: null }).sort({ date: -1 });
        res.json({ success: true, data: records });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};

export const createPnLRecord = async (req, res) => {
    try {
        const expenseFields = ['rawMaterial', 'labourSalary', 'supervisorQC', 'electricity', 'firewood', 'packing', 'transport', 'communication', 'other'];
        const totalExp = expenseFields.reduce((acc, field) => acc + (Number(req.body[field]) || 0), 0);
        const revenue = Number(req.body.totalRevenue) || 0;
        const netProfit = revenue - totalExp;
        const marginPercent = revenue > 0 ? +((netProfit / revenue) * 100).toFixed(2) : 0;

        const record = await DailyPnL.create({
            ...req.body,
            totalExpenses: totalExp,
            netProfit: netProfit,
            marginPercent: marginPercent,
            createdBy: req.user?._id
        });

        // Sync to Excel
        try {
            await excelService.updateExcelRow('pnl', record);
        } catch (e) {
            // Non-blocking
        }

        res.status(201).json({ success: true, data: record });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};

export const updatePnLRecord = async (req, res) => {
    try {
        const expenseFields = ['rawMaterial', 'labourSalary', 'supervisorQC', 'electricity', 'firewood', 'packing', 'transport', 'communication', 'other'];
        const totalExp = expenseFields.reduce((acc, field) => acc + (Number(req.body[field]) || 0), 0);
        const revenue = Number(req.body.totalRevenue) || 0;
        const netProfit = revenue - totalExp;
        const marginPercent = revenue > 0 ? +((netProfit / revenue) * 100).toFixed(2) : 0;

        const record = await DailyPnL.findByIdAndUpdate(
            req.params.id,
            { ...req.body, totalExpenses: totalExp, netProfit: netProfit, marginPercent: marginPercent, updatedBy: req.user?._id },
            { new: true }
        );

        if (!record) return res.status(404).json({ success: false, message: 'Record not found' });

        // Sync to Excel
        try {
            await excelService.updateExcelRow('pnl', record);
        } catch (e) {
            // Non-blocking
        }

        res.json({ success: true, data: record });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};

export const deletePnLRecord = async (req, res) => {
    try {
        const record = await DailyPnL.findByIdAndUpdate(req.params.id, { deletedAt: new Date() }, { new: true });
        if (!record) return res.status(404).json({ success: false, message: 'Record not found' });

        // Sync to Excel (Delete row)
        try {
            await excelService.deleteExcelRow('pnl', record);
        } catch (e) {
            // Non-blocking
        }

        res.json({ success: true, message: 'Record deleted' });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};

export const getDailyPnLCalculation = async (req, res) => {
    try {
        const { date } = req.query;
        if (!date) {
            return res.status(400).json({ success: false, message: 'Date parameter is required' });
        }

        const calculated = await calculatePnLForDate(date);
        res.json({
            success: true,
            data: calculated
        });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};

export const autoGenerateAllDailyPnL = async (req, res) => {
    try {
        const { startDate, endDate } = req.body || {};
        const records = await autoGenerateDailyPnLRecords({
            startDate,
            endDate,
            userId: req.user?._id
        });

        res.json({
            success: true,
            count: records.length,
            message: `Successfully auto-generated and synced ${records.length} Daily P&L records from system data`,
            data: records
        });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};
