import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';

/**
 * Export data to CSV
 * @param {Array} data - Array of objects
 * @param {string} fileName - File name with extension
 */
export const exportToCSV = (data, fileName = 'export.csv') => {
    if (!data.length) return;
    
    const headers = Object.keys(data[0]);
    const csvRows = [];
    
    // Add headers
    csvRows.push(headers.join(','));
    
    // Add data rows
    for (const row of data) {
        const values = headers.map(header => {
            const escaped = ('' + row[header]).replace(/"/g, '\\"');
            return `"${escaped}"`;
        });
        csvRows.push(values.join(','));
    }
    
    const csvContent = csvRows.join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    
    if (link.download !== undefined) {
        const url = URL.createObjectURL(blob);
        link.setAttribute('href', url);
        link.setAttribute('download', fileName);
        link.style.visibility = 'hidden';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    }
};

/**
 * Export data to Excel
 */
export const exportToExcel = (data, fileName = 'export', sheetName = 'Data') => {
    const worksheet = XLSX.utils.json_to_sheet(data);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
    XLSX.writeFile(workbook, `${fileName}.xlsx`);
};

/**
 * Export data to PDF with professional layout
 */
export const exportToPDF = (title, columns, data, fileName = 'report', metadata = {}) => {
    const doc = new jsPDF({
        orientation: columns.length > 6 ? 'landscape' : 'portrait',
        unit: 'mm',
        format: 'a4'
    });
    
    const pageWidth = doc.internal.pageSize.width;
    
    // 1. Header Section
    doc.setFillColor(37, 99, 235); // primary-600
    doc.rect(0, 0, pageWidth, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('WHOLESALE ERP', 14, 20);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Enterprise Resource Management System', 14, 28);
    
    // 2. Report Info (Right-aligned)
    doc.setFontSize(14);
    doc.text(title.toUpperCase(), pageWidth - 14, 20, { align: 'right' });
    
    doc.setFontSize(9);
    doc.text(`Report Date: ${new Date().toLocaleString()}`, pageWidth - 14, 28, { align: 'right' });
    if (metadata.userName) {
        doc.text(`Generated by: ${metadata.userName} (${metadata.userRole || 'User'})`, pageWidth - 14, 34, { align: 'right' });
    }

    // 3. Table Section
    doc.autoTable({
        startY: 50,
        head: [columns.map(col => col.header)],
        body: data.map(item => columns.map(col => {
            const val = item[col.dataKey];
            if (val === null || val === undefined) return '—';
            if (typeof val === 'number') return val.toLocaleString('en-LK', { minimumFractionDigits: 2 });
            if (typeof val === 'object') return val.name || val.code || JSON.stringify(val);
            return String(val);
        })),
        theme: 'striped',
        headStyles: { 
            fillColor: [30, 41, 59], // slate-800
            textColor: [255, 255, 255],
            fontSize: 9,
            fontStyle: 'bold',
            halign: 'center'
        },
        styles: { 
            fontSize: 8,
            cellPadding: 3,
            valign: 'middle'
        },
        alternateRowStyles: {
            fillColor: [248, 250, 252] // slate-50
        },
        margin: { left: 14, right: 14 },
        didDrawPage: (data) => {
            // Footer
            const str = `Page ${doc.internal.getNumberOfPages()}`;
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(str, pageWidth - 14, doc.internal.pageSize.height - 10, { align: 'right' });
            doc.text('Confidential - System Generated Report', 14, doc.internal.pageSize.height - 10);
        }
    });
    
    doc.save(`${fileName}.pdf`);
};
